name: CD - Update Kubernetes Manifests

on:
  push:
    branches:
      - main
    paths:
      - 'Kubernetes/**'
  workflow_dispatch:
    inputs:
      REPO_IMAGE:
        description: 'Frontend Docker tag of the image built by the CI job'
        required: true
      IMAGE_NAME:
        description: 'Backend Docker tag of the image built by the CI job'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Clean workspace → GitHub provides a fresh one each run
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }} # personal access token or PAT with repo write access

      - name: Verify Docker Image Tags
        run: |
          echo "LOCAL_DOCKER_IMAGES: ${{ github.event.inputs.IMAGE_NAME }}"
          echo "DOCKER_HUB_IMAGES: ${{ github.event.inputs.REPO_IMAGE }}"

      - name: Update Kubernetes manifests
        run: |
          cd Kubernetes
          sed -i "s|shailesh49/netflix:[^\"']*|${{ github.event.inputs.REPO_IMAGE }}|g" deployment.yml

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          echo "Checking repository status: "
          git status

          echo "Adding changes to git: "
          git add .

          echo "Committing changes: "
          git commit -m "Updated deployment image to ${{ github.event.inputs.REPO_IMAGE }}" || echo "No changes to commit"

          echo "Pushing changes to GitHub: "
          git push origin main
